apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.24.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: es02
  name: es02
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: es02
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.24.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: es02
    spec:
      containers:
        - env:
            - name: bootstrap.memory_lock
              value: "false"
            - name: cluster.initial_master_nodes
              value: es01,es02,es03
            - name: cluster.name
              value: docker-cluster
            - name: discovery.seed_hosts
              value: es01,es03
            - name: node.name
              value: es02
            - name: xpack.license.self_generated.type
              value: basic
            - name: xpack.security.enabled
              value: "true"
            - name: xpack.security.http.ssl.certificate
              value: certs/es02/es02.crt
            - name: xpack.security.http.ssl.certificate_authorities
              value: certs/ca/ca.crt
            - name: xpack.security.http.ssl.enabled
              value: "true"
            - name: xpack.security.http.ssl.key
              value: certs/es02/es02.key
            - name: xpack.security.http.ssl.verification_mode
              value: certificate
            - name: xpack.security.transport.ssl.certificate
              value: certs/es02/es02.crt
            - name: xpack.security.transport.ssl.certificate_authorities
              value: certs/ca/ca.crt
            - name: xpack.security.transport.ssl.enabled
              value: "true"
            - name: xpack.security.transport.ssl.key
              value: certs/es02/es02.key
            - name: xpack.security.transport.ssl.verification_mode
              value: certificate
          image: docker.elastic.co/elasticsearch/elasticsearch:8.1.0
          name: es02
          resources:
            limits:
              memory: "1073741824"
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/config/certs
              name: certs
            - mountPath: /usr/share/elasticsearch/data
              name: esdata02
      restartPolicy: Always
      volumes:
        - name: certs
          persistentVolumeClaim:
            claimName: certs
        - name: esdata02
          persistentVolumeClaim:
            claimName: esdata02
status: {}
