apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.24.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: kibana
  name: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kibana
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.24.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: kibana
    spec:
      containers:
        - env:
            - name: ELASTICSEARCH_HOSTS
              value: https://es01:9200
            - name: ELASTICSEARCH_PASSWORD
              value: liuchao123456
            - name: ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES
              value: config/certs/ca/ca.crt
            - name: ELASTICSEARCH_USERNAME
              value: kibana_system
            - name: SERVERNAME
              value: kibana
          image: docker.elastic.co/kibana/kibana:8.1.0
          name: kibana
          ports:
            - containerPort: 5601
          resources:
            limits:
              memory: "1073741824"
          volumeMounts:
            - mountPath: /usr/share/kibana/config/certs
              name: certs
            - mountPath: /usr/share/kibana/data
              name: kibanadata
      restartPolicy: Always
      volumes:
        - name: certs
          persistentVolumeClaim:
            claimName: certs
        - name: kibanadata
          persistentVolumeClaim:
            claimName: kibanadata
status: {}
