kind: Deployment
apiVersion: apps/v1
metadata:
  name: logging-app-manual
spec:
  replicas: 1
  selector:
    matchLabels:
      name: logging-app-manual
  template:
    metadata:
      labels:
        name: logging-app-manual
    spec:
      hostname: logging-app-manual
      containers:
        - name: beat-manual
          image: docker.elastic.co/beats/filebeat:8.1.0
          args: [
            "-c", "/etc/filebeat/filebeat.yml",
            "-e"
          ]
          volumeMounts:
            - name: beat-manual-config
              mountPath: /etc/filebeat/
            - name: manual-log-directory
              mountPath: /mnt/logs/
        - name: logging-app-manual
          image: com.lctest/mydockerstrap:0.0.1
          volumeMounts:
            - name: manual-log-directory
              mountPath: /mnt/logs/
      volumes:
        - name: beat-manual-config
          configMap:
            name: beat-manual-config
            items:
              - key: filebeat.yml
                path: filebeat.yml
        - name: manual-log-directory
          emptyDir: {}
