apiVersion: v1
kind: Service
metadata:
  name: my-elasticsearch
  labels:
    app: my-elasticsearch
spec:
  type: NodePort
  selector:
    app: my-elasticsearch
  ports:
  - name: http
    port: 9200
    nodePort: 30920
