filebeat.inputs:
- type: container
  paths:
    - /var/log/containers/*.log
  processors:
    - add_kubernetes_metadata:
        host: ${NODE_NAME}
        matchers:
        - logs_path:
            logs_path: "/var/log/containers/"
- type: log
  paths:
    - /mnt/output.log
# To enable hints based autodiscover, remove `filebeat.inputs` configuration and uncomment this:
#filebeat.autodiscover:
#  providers:
#    - type: kubernetes
#      node: ${NODE_NAME}
#      hints.enabled: true
#      hints.default_config:
#        type: container

#          - /var/log/containers/*${data.kubernetes.container.id}.log

processors:
  - add_cloud_metadata:
  - add_host_metadata:

cloud.id: ${ELASTIC_CLOUD_ID}
cloud.auth: ${ELASTIC_CLOUD_AUTH}

output:
#  输出到logstash中,logstash更换为自己的ip
  logstash:
    hosts: ["10.252.203.240:30044"]

#output.elasticsearch:
#  hosts: ["http://10.252.203.240:30920"]
#  username:
#  password:
#  allow_older_versions: true

#output.elasticsearch:
#  hosts: ["https://es01:9200","https://es02:9200","https://es03:9200"]
#  username: elastic
#  password: liuchao123456
